#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 16 15:33:03 2019

@author: Giles
"""

# 1 Ask the user for the radius of a circle and then print the area



# 2 Convert fahrenheit to celsius (You will have to find the formula)



# 3 Obtain the sum of two integers


# 4 Obtain the product of two integers


# 5 Bob, Ann, Jane and Ashwin want to order pizza - they know they will each eat
# 4 slices of pizza. The local pizza shop sells pizzas of only 6 slices
# What is the minimum number of pizzas needed - Use floor division
